DEBUG: True
seed: ~

# experiment settings
EXP_NAME: 'Auto lens design'

# lens target example 1 (camera lens)
foclen: 85.0
fov: 40.0
fnum: 4.0
flange: 18.0
thickness: 120.0
lens_type: [["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric", "Spheric"], ["Aperture"], ["Spheric", "Spheric"], ["Spheric", "Aspheric"], ["Spheric", "Aspheric"]]
lrs: [5e-4, 1e-3, 1e-1, 1e-3]
decay: 0.001

# # lens target example 2 (mobile lens)
# foclen: 6.0
# fov: 70.0
# fnum: 2.0
# flange: 1.0
# thickness: 9.0
# lens_type: [["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
# lrs: [3e-4, 1e-4, 1e-1, 1e-2]
# decay: 0.01